# Generated by Django 3.2 on 2024-02-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('anonymous', 'аноним'), ('user', 'юзер'), ('moderator', 'модератор'), ('admin', 'админ'), ('superadmin', 'суперадмин')], default='user', max_length=16, verbose_name='Пользовательская роль'),
        ),
    ]
