# Generated by Django 3.2 on 2024-02-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_extendeduser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
