# Generated by Django 3.2 on 2024-02-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240213_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('anonymous', 'аноним'), ('user', 'юзер'), ('moderator', 'модератор'), ('admin', 'админ'), ('superadmin', 'суперадмин')], default='юзер', max_length=16, verbose_name='Пользовательская роль'),
        ),
    ]
