# Generated by Django 3.2 on 2024-02-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('anonymous', 'аноним'), ('user', 'юзер'), ('moderator', 'модератор'), ('admin', 'админ'), ('superadmin', 'суперадмин')], default='user', max_length=16, verbose_name='Пользовательская роль'),
        ),
    ]
